name: fraud-batch-inference-pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  schedule:
    - cron: "11 11 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v5

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv and just
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Setup Python virtual environment
        run: |
          uv venv
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Setup development environment
        run: |
          uv pip install '.[dev]'
          pre-commit install

      - name: Run fraud batch inference
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: just fraud-inference
